name: Pylint + Black

on: 
  push:
    branches: [ "main" ] # Ejecutar solo en 'main' o las ramas que definas
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4 # 1. Clonar el repositorio

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependencias, Pylint y Black
      run: |
        python -m pip install --upgrade pip
        
        # Buscar y instalar dependencias desde requisitos.txt
        REQS=$(find . -name requisitos.txt)
        if [ -n "$REQS" ]; then
          echo "Se encontraron archivos de requisitos:"
          echo "$REQS"
          for req in $REQS; do
            echo "Instalando dependencias desde $req..."
            pip install -r "$req"
          done
        else
          echo "No se encontraron archivos requisitos.txt. Omitiendo instalación de dependencias."
        fi
        
        # 2. Instalar Pylint y Black
        pip install pylint black

    - name: Ejecutar formateador Black
      run: |
        echo "Verificando formato de código con Black..."
        black --line-length 100 .

    - name: Analizando el código con Pylint
      run: |
        # 4. Ejecutar Pylint en todos los archivos .py rastreados por Git
        export PYTHONPATH=$PYTHONPATH:$(pwd)/unidad_7/pystock_management
        pylint $(git ls-files '*.py')